- name: Ansible Jenkins Playbook
  remote_user: vagrant
  become: yes
  hosts: TEST
  tasks:
    - name: Install Java
      command: yum install -y java-1.8.0-openjdk
    - name: Download Artifact
      get_url:
        url: http://192.168.0.105:8081/service/rest/v1/search/assets/download?sort=version&maven.groupId=com.jenkins&maven.artifactId=testPipeline&maven.extension=jar
        dest: /opt/
    
